api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

#Create router instance
router = routers.SimpleRouter()
#specify that all the views in the List set to start with url "lists"
router.register(r'lists', views.ListViewSet)
#specify that all the views in the List set to start with url "entries"
router.register(r'entries', views.EntryViewSet)
#specify that all the views in the List set to start with url "comment"
router.register(r'comments', views.CommentViewSet)
#test route

urlpatterns = [
	url(r'^$', views.test.as_view()),
    url(r'^v2/', include(router.urls, namespace='apiv2')),
	url(r'^buttons/', views.ButtonResponse.as_view()),
]	

trackerbot/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from rest_framework import routers
from api import views
from website import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('api.urls')),
    url(r'^', include('website.urls', namespace='website')),
]

website/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
	url(r'^login/$', views.SlackAuthorization, name='login'),
	url(r'^$', views.HomeView.as_view(), name='home'),
	url(r'^lists/$', views.ListListView.as_view(), name='list'),
	url(r'^lists/(?P<pk>\d+)/$', views.ListDetailView.as_view(), name='listdetail'),
	url(r'^lists/create/$', views.ListCreateView.as_view(), name='createlist'),
	url(r'^lists/edit/(?P<pk>\d+)/$', views.ListUpdateView.as_view(), name='updatelist'),
	url(r'^lists/delete/(?P<pk>\d+)/$', views.ListDeleteView.as_view(), name='deletelist'),
	url(r'^entries/(?P<pk>\d+)/$', views.EntryDetailView.as_view(), name='entrydetail'),
	url(r'^entries/edit/(?P<pk>\d+)/$', views.EntryUpdateView.as_view(), name='updateentry'),
	url(r'^entries/delete/(?P<pk>\d+)/$', views.EntryDeleteView.as_view(), name='deleteentry'),
	url(r'^vote/(?P<user>\d+)/(?P<pk>\d+)/$', views.HomeView.as_view(), name="vote"),
]

website/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class SlackAuth(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	access_token = models.CharField(max_length=255)
	team_id = models.CharField(max_length=255)
	name = models.CharField(max_length=50)
	slack_id = models.CharField(max_length=50)
	avatar = models.CharField(max_length=255)
	email = models.EmailField(max_length=254)

website/forms.py
from api import models
from django import forms

class EntryForm(forms.ModelForm):
	
	class Meta:
		model = models.Entry
		fields = ('entrydescription', )
		
	def __init__(self, *args, **kwargs):
		super(EntryForm,self).__init__(*args, **kwargs)
		self.fields['entrydescription'].widget = forms.TextInput(attrs={
			'class': 'textfield',
			'placeholder': 'Add a new entry '
			})

class CommentForm(forms.ModelForm):
	
	class Meta:
		model = models.Comment
		fields = ('comment',)

class ListForm(forms.ModelForm):
	name = forms.CharField( label='')
	class Meta:
		model = models.List
		fields = ('name',)

website/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (TemplateView, ListView, DetailView,
								  CreateView, UpdateView, DeleteView,
								  FormView)
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import messages
import requests
import json
import random
from models import SlackAuth
from api import models
from . import forms
# Create your views here.


def SlackAuthorization(request):
	token = request.GET['code']
	r = requests.get('https://slack.com/api/oauth.access?client_id={}&client_secret={}&code={}'.format(
		settings.SLACK_CLIENT_ID, settings.SLACK_CLIENT_SECRET, token)).json()
	access_token = r['access_token']
	team_id = r['team']['id']
	if team_id == settings.TEAM_ID:
		slackuser = r['user']
		slack_id = slackuser['id']
		name = slackuser['name']
		email = slackuser['email']
		avatar = slackuser['image_1024'].replace('\\','')
		user, created = User.objects.get_or_create(username=email)
		if created:
			user.set_password(access_token)
			user.save()
			SlackAuth.objects.create(user=user, access_token=access_token,
								  team_id=team_id, name=name, slack_id=slack_id,
								  avatar=avatar, email=email)
			user.save()
		login(request, user)
		return redirect('website:list')
	else:
		messages.add_message(request, messages.INFO, "You must be a part of the BluestoneLogic")
		return redirect('website:home')

class HomeView(TemplateView):
	template_name = 'index.html'

	def get_context_data(self, **kwargs):
		context = super(HomeView, self).get_context_data(**kwargs)
		if messages.get_messages(self.request):
			context["message"] = messages.get_messages(self.request)
		return context

	# def dispatch(self, request, *args, **kwargs):
 #         if self.request.user.is_authenticated():
 #         	return redirect('website:list')
 #         return super(HomeView, self).dispatch(request, *args, **kwargs)
'''
Generic CRUD for lists
'''
class ListListView(LoginRequiredMixin,FormMixin, ListView):
	model = models.List
	context_object_name = "lists"
	template_name = "list_lists.html"
	login_url = reverse_lazy('website:home')
	form_class = forms.ListForm

	def get_success_url(self):
		return reverse_lazy('website:list')

	def get_context_data(self, **kwargs):
		context = super(ListListView, self).get_context_data(**kwargs)
		context['form'] = self.get_form()
		return context

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return HttpResponseForbidden()
		form = self.get_form()
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	def form_valid(self, form):
		f = form.save(commit=False)
		f.creator_id = SlackAuth.objects.filter(user=self.request.user)[0].pk
		f.save()
		return super(ListListView, self).form_valid(form)

class ListDetailView(LoginRequiredMixin, DetailView, FormMixin):
	model = models.List
	template_name = "list_detail.html"
	form_class = forms.EntryForm

	def get_success_url(self):
		return reverse_lazy('website:listdetail', kwargs={'pk':self.object.pk})

	def get_context_data(self, **kwargs):
		context = super(ListDetailView, self).get_context_data(**kwargs)
		entries = models.Entry.objects.filter(parent=context['list'])
		context['entries'] = {}
		context['curruser'] = SlackAuth.objects.filter(user=self.request.user)[0]
		for entry in entries:
			context['entries'][entry] = {}
			votes = models.Vote.objects.filter(parententry=entry)
			upvotes = votes.filter(vote="UPVOTE")
			downvotes = votes.filter(vote="DOWNVOTE")
			context['entries'][entry]["upvotes"] = len(upvotes)
			context['entries'][entry]["downvotes"] = len(downvotes)
		context['form'] = self.get_form()
		return context

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return HttpResponseForbidden()
		self.object = self.get_object()
		form = self.get_form()
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	def form_valid(self, form):
		parent = get_object_or_404(models.List, pk=self.object.pk)
		f = form.save(commit=False)
		f.username = SlackAuth.objects.filter(user=self.request.user)[0].name
		f.parent = parent
		f.save()
		return super(ListDetailView, self).form_valid(form)

def UpdateVote(request):
	print request
	return reverse('website:list')

class ListCreateView(LoginRequiredMixin, CreateView):
	fields = ("name",)
	model = models.List
	template_name = "list_form.html"

	def form_valid(self, form):
		f = form.save(commit=False)
		f.creator = SlackAuth.objects.filter(user=self.request.user)[0]
		f.save()
		return super(ListCreateView, self).form_valid(form)

class ListUpdateView(LoginRequiredMixin, UpdateView):
	fields = ("name",)
	model = models.List
	template_name = "list_form.html"

class ListDeleteView(LoginRequiredMixin, DeleteView):
	model=models.List
	success_url = reverse_lazy("website:list")
	template_name = "list_confirm_delete.html"

	def get_queryset(self):
		if not self.request.user.is_superuser:
			return self.model.objects.filter(creator=SlackAuth.objects.filter(user=self.request.user)[0])
		return self.model.objects.all()

class EntryDetailView(LoginRequiredMixin, DetailView, FormMixin):
	model = models.Entry
	template_name = "entry_detail.html"
	form_class = forms.CommentForm

	def get_context_data(self, **kwargs):
		context = super(EntryDetailView, self).get_context_data(**kwargs)
		context['comments'] = models.Comment.objects.filter(parent=context['entry'])
		context['form'] = self.get_form()
		return context

	def get_success_url(self):
		return reverse_lazy('website:entrydetail', kwargs={'pk':self.object.pk})


	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return HttpResponseForbidden()
		self.object = self.get_object()
		form = self.get_form()
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	def form_valid(self, form):
		parent = get_object_or_404(models.Entry, pk=self.object.pk)
		f = form.save(commit=False)
		f.name = SlackAuth.objects.filter(user=self.request.user)[0].name
		f.parent = parent
		f.save()
		return super(EntryDetailView, self).form_valid(form)

class EntryCreateView(LoginRequiredMixin, CreateView):
	fields = ("entrydescription","username")
	model = models.Entry
	template_name = "entry_form.html"

	def get_initial(self):
		inital = super(EntryCreateView, self).get_initial(self)
		inital["username"] = SlackAuth.objects.filter(user=self.request.user)[0].name

class EntryUpdateView(LoginRequiredMixin, UpdateView):
	fields = ("entrydescription",)
	model = models.Entry
	template_name = "entry_form.html"

class EntryDeleteView(LoginRequiredMixin, DeleteView):
	model = models.Entry
	template_name = "entry_confirm_delete.html"

	def get_success_url(self):
		return reverse_lazy('website:listdetail', args = (self.object.parent.pk,))

website/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href ="{% static 'css/bootstrap-theme.css' %}">
		<link rel="stylesheet" href ="{% static 'css/bootstrap-theme.min.css' %}">
		<link rel="stylesheet" href ="{% static 'css/bootstrap.css' %}">
		<link rel="stylesheet" href = "{% static 'css/style.css' %}">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	</head>
  		{% block parent %}
  		{% endblock %}
</html>

website/templates/entry_confirm_delete.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}Delete {{ entry.entrydescription }}{% endblock %}
{% block parent %}
	<h1>Are you sure you want to delete {{ entry.entrydescription }}?</h1>
	<form method='POST'>
	<input type="submit" class="btn btn-danger" value="Delete"><a href="{% url 'website:listdetail' pk=entry.parent.pk %}">Cancel</a>
	</form>
{% endblock parent %}

website/templates/entry_detail.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}Comment Detail{% endblock %}
{% block parent %}
	<row>
	<div class="col-md-12 center">
	<h1>{{ entry.entrydescription }}</h1>
	{% if comments %}
	{% for comment in comments %}
	<div>
	<ul>
	<li>{{ comment.comment }} | {{ comment.created_date }} | {{ comment.name }} </li>
	</ul>
	</div>
	{% endfor %}
	{% else %}
	<div>Currently no Comments</div>
	{% endif %}
	</div>
	<hr>
	<form method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="btn btn-primary" value="Save">
	<hr>
	<p>
	<a href = "{% url 'website:updateentry' pk=entry.pk %}" class="btn btn-primary">Edit Entry</a>
	<a href = "{% url 'website:deleteentry' pk=entry.pk %}" class="btn btn-danger">Delete Entry</a>
	</p>
    </row>
{% endblock parent %}

website/templates/entry_form.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}New List{% endblock %}
{% block parent %}
<h1>{% if not form.instance.pk %}Create a new Entry{% else %}Edit {{ form.instance.entrydescription }}{% endif %}
</h1>
	<row>
	<div class="col-md-12 center">
	<form method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="btn btn-primary" value="Save">
	</form>
	</div>
    </row>
{% endblock parent %}

website/templates/index.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}Login{% endblock %}
{% block parent %}
	<div style="width: 100%; height:100%;">
	<div style="width:100%; height:16vh;">
	</div>
	<div class="center" id="landing">
		<img id="logo" src="{% static 'stonestack.svg' %}"/>
        <h1 id="title">Stonestacks</h1>
<a href="https://slack.com/oauth/authorize?scope=identity.basic,identity.email,identity.avatar&client_id=2989721246.157603362881"><img alt="Sign in with Slack" height="40" width="172" src="https://platform.slack-edge.com/img/sign_in_with_slack.png" srcset="https://platform.slack-edge.com/img/sign_in_with_slack.png 1x, https://platform.slack-edge.com/img/sign_in_with_slack@2x.png 2x" /></a>
	<div class="message">
	{% for message in messages %}
	    <p>{{ message }}</p>
	    {% endfor %}</div>
	</div>
	</div>
{% endblock parent %}

website/templates/list_confirm_delete.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}Delete {{ list.name }}{% endblock %}
{% block parent %}
	<h1>Are you sure you want to delete {{ list.name }}?</h1>
	<form method='POST'>
	<input type="submit" class="btn btn-danger" value="Delete"><a href="{% url 'website:listdetail' pk=list.pk %}">Cancel</a>
	</form>
{% endblock parent %}

website/templates/list_detail.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}List Detail{% endblock %}
{% block parent %}
<div style="background-color: #f2f2f2; width: 100vw; height: 100vh;">
	<row>
	<div class="center">
	<div id="listdetail">
	<a href= "{% url 'website:list'%}"><img id="logodetail" src="{% static 'stonestack.svg' %}"/></a>
	<span id="listdetailtitle">{{ list.name }}</span>
	</div>
	{% if entries %}
	{% for entry, val in entries.items %}
	<div class="entrycontainer">
	<div style="padding-left: 10px;">
	<img src="{{ entry.getUser.avatar }}" style="float: left; width: 55px; height: 55px; -moz-border-radius: 50px;
	-webkit-border-radius: 50px;" /></div>
	<div class="updown" style="float: right; padding: 6px;"><a href="{% url 'website:vote' user=entry.getUser.pk pk=entry.pk %}"><span style="color:#54C28F; text-shadow: 0 1px 1px rgba(0,0,0,0.15);">▲</span></a>: {{ val.upvotes }}<br><span style="color:#E53E4C; text-shadow: 0 1px 1px rgba(0,0,0,0.15);">▼</span>: {{ val.downvotes }}</div>
	
	{{ entry.entrydescription }}<br><br><br>
	<a href = "{% url 'website:entrydetail' pk=entry.pk %}" class="btn btn-primary" style="float: right;">Comments: {{ entry.getComments}}</a>
	{% if curruser == list.creator %}
	<a href = "{% url 'website:updateentry' pk=entry.pk %}" class="btn btn-info" style="float: right;">Edit</a>
	<a href = "{% url 'website:deleteentry' pk=entry.pk %}" class="btn btn-danger" style="float: right;">Delete</a>
	{% endif %}
	<div>
	</div>
	<div id="entry"><p style="float:left;">
	{{ entry.username }} posted on {{ entry.created_at }}</div>	</p>
	</div>
	<hr>
	{% endfor %}
	{% else %}
	<div>Currently no entries</div>
	{% endif %}
	</div>
	<div class="center">
	<form method='POST'>
		{% csrf_token %}
		{{ form.entrydescription}}
		<br>
		<input type="submit" class="btn btn-primary" value="Create Entry">
	</form>
	</div>
    </row>
</div>
{% endblock parent %}

website/templates/list_form.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}New List{% endblock %}
{% block parent %}
<h1 class="center">{% if not form.instance.pk %}Create a new List{% else %}Edit {{ form.instance.name }}{% endif %}
</h1>
	<row>
	<div class="col-md-12 center">
	<form method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="btn btn-primary" value="Save">
	</div>
    </row>
{% endblock parent %}

website/templates/list_lists.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}Lists{% endblock %}
{% block parent %}
	<row>
	<div class="main center">
	{% if lists %}
		{% for list in lists %}
	<a href = '{% url "website:listdetail" pk=list.pk %}'>
		<div class="listbox" id="wrap{{list.pk}}">
			<div class="listtitlebox">
			<div class="firstletterbox" style="background-color:#{{ list.randomColor }}">
			<span id="firstletter">{{ list.name|make_list|first|upper }}</span></div>
			<span id="listtitle">{{ list.name }}</span>
			</div></a>
			<div class="listboxdrop" id="list{{list.pk}}">
			{% if list.getEntries %}
			{% for entry in list.getEntries %}<hr>
			<p><a href='{{ entry.get_absolute_url }}'>{{ entry.entrydescription }}</span><br><span style="color:Green">▲</span> {{entry.upVotes}} <span style="color:Red">▼</span> {{entry.downVotes}}</span><br></a></p>
			{% endfor %}
			{% else %}
			<p> No Entries </p>
			{% endif %}
			</div>
		</div>
		<script type="text/javascript">
		$(document).ready(function(){
		  $("#wrap{{list.pk}}").mouseover(function(){
		   $("#list{{list.pk}}").toggleClass("active");
		  });
		  $("#wrap{{list.pk}}").mouseout(function(){
		   $("#list{{list.pk}}").toggleClass("active");
		  });
		 });
		</script>
		{% endfor %}	
	{% endif %}
	<div class="listbox" id="ugh">
	<div class="listtitleboxa" style="background-color:#36519A;">
	<div class="firstletterboxa">
	<span id="addnew">
		<span style="font-size: 70px">+</span><br>
	</span>
	</div>
	</div>
	<div class="listboxdrop" id="addform">
	<form method='POST' class="listform">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="btn btn-primary" value="Create">
	</form>
	</div>
	</div>
	</div>
    </row>
    	<script type="text/javascript">
		$(document).ready(function(){
		$(".firstletterboxa").click(function(){
			   $("#addform").toggleClass("active");
			});
		});
	</script>
 
{% endblock parent %}